### PR TITLE
feat(firebase): add Google Account auth

### PR DESCRIPTION
**Pull request by penx**
Reopening https://github.com/remix-run/remix/pull/4057 against remix-run/examples

Firebase example - Integration with Google Sign-in Provider

Closes: "sign-in with Google" suggestion at https://github.com/remix-run/remix/pull/1811#issuecomment-1050238130

Adds a "Login with Google" link:

> Screenshot 2022-08-24 at 15 16 57

...that takes a user to the Google's auth screen:

> Screenshot 2022-08-24 at 15 17 22

 ...and then creates an account (if it doesn't yet exist) and signs them in:

> Screenshot 2022-08-24 at 15 19 26

### CODE REVIEW

**Review by machour — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@penx Could you please fix the ESLint warnings/errors?

**Comment by MichaelDeBoey** [comment]
@penx Could you please fix the ESLint warnings/errors?
Most of them will probably be fixed by running `yarn lint:fix`

**Comment by MichaelDeBoey** [comment]
@penx Could you please fix the ESLint warnings/errors?
Most of them will probably be fixed by running `yarn lint:fix`

Please also resolve conflicts.

**Comment by penx** [comment]
@MichaelDeBoey please can you reopen this? github-actions pretty quick to close.

I'll resolve conflicts now. I'd already [fixed issues and resolved conflicts on 4 October](https://github.com/remix-run/examples/pull/4#event-7519792262) but will do again :)

**Comment by machour** [comment]
@MichaelDeBoey unable to reopen on my side:
Screen Shot 2022-10-31 at 1 50 17 PM

**Comment by penx** [comment]
@MichaelDeBoey @machour ok no worries, I'll open new PRs for this and #5

**Pull request closed without merging**
