### PR TITLE
chore(socket.io): rename to `socket-io`

### LINKED ISSUE #267: Using template as specified does not seem to work
tl;dr can we please update [the readme](https://github.com/remix-run/examples/blob/e2f3e70a367d2057dcfd65724a24a823ba524077/README.md) to have template instructions that will work for an impatient noob?

Hello!

I'm new to remix and love it!

The examples are great but I had a tough time using one of the examples as a template.

## Problem

In [the readme](https://github.com/remix-run/examples/blob/e2f3e70a367d2057dcfd65724a24a823ba524077/README.md) I followed the instructions:

> You can also initialize a new project with any of these examples using the --template flag of the create-remix CLI.

And used the example `npx create-remix@latest --template examples/<example-dir>`

Running this on my own, to use the [socket.io example](https://github.com/remix-run/examples/tree/e2f3e70a367d2057dcfd65724a24a823ba524077/socket.io), I ran the following command:

```
npx create-remix@latest --template examples/socket.io
```

However, I received the following error:

```
🚨 Invalid template selected. Please try again.
```

## Solution

After reviewing the [docs related to templates](https://github.com/remix-run/remix/blob/29329819c62208553861cc11982f904cf1b5e79e/docs/other-api/dev.md#remix-create---template) I experimented with a few possibilities.

These did not work for me:

```
npx create-remix@latest --template examples/main/socket.io
npx create-remix@latest --template remix-run/examples/blob/main/socket.io
npx create-remix@latest --template remix-run/examples/socket.io
```

Finally, using the full github path, this did work for me:

```
npx create-remix@latest --template https://github.com/remix-run/examples/tree/main/socket.io
```

My solution I believe is overly verbose than necessary, but if we can update the readme to have an example that will definitely run that would be great.

Thanks again for an amazing product!

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #267

### CODE REVIEW

**Comment by brophdawg11** [comment]
Is there a way we can fix this in the CLI?  It seems prohibitive to have to say "templates cannot contain a dot".  What are the supported extensions if pointing to a file - `.tgz` and maybe `.git`?  Maybe we can only try to download the file if it matches those and otherwise treat it as a folder in a repo?

**Comment by brophdawg11** [comment]
@markdalgleish Do you know if this is still an issue in the new v2 create-remix CLI?  If so is it something we can handle?

**Comment by MichaelDeBoey** [comment]
Just tried this out and got the following error:

```sh
      ◼  Directory: Using test-project as project directory

      ◼  Template: Using remix-run/examples/socket.io...

      ▲  Oh no! "examples/socket.io" is an invalid template. Run create-remix --help to see supported template formats.
```

Same when trying with `remix-run/examples/socket.io`:

```sh
      ◼  Directory: Using test-project as project directory

      ◼  Template: Using remix-run/examples/socket.io...

      ▲  Oh no! "remix-run/examples/socket.io" is an invalid template. Run create-remix --help to see supported template formats.
```

**Comment by brophdawg11** [comment]
I'm going to close this in favor of allowing shorthand folders to contain dots in https://github.com/remix-run/remix/pull/7277

**Pull request closed without merging**
