### PR TITLE
feat(firebase): deploy to Cloud Functions for Firebase

### PR DESCRIPTION
**Pull request by penx**
Reopening #5, https://github.com/remix-run/remix/pull/3398 against remix-run/examples

Deploy to firebase functions and hosting

Closes: Discussion at https://github.com/remix-run/remix/pull/1811#issuecomment-1050238130

- [x] Docs
- [ ] Tests (I'd happily add Playwright tests if you want these on examples)

Testing Strategy:

- Testing locally against emulator with JS enabled and disabled
- Testing locally against production with JS enabled and disabled
- Following deploy instructions and testing remote with JS enabled and disabled

### CODE REVIEW

**Comment by penx** [comment]
@machour @mcansh @MichaelDeBoey

Similar to my comment on https://github.com/remix-run/examples/pull/52#issuecomment-1398359960

Please let me know if I should keep rebasing this or abandon it

**Comment by MichaelDeBoey** [comment]
@penx Please rebase this branch onto latest `main` & resolve conflicts

**Review by mcansh — APPROVED** [review]

**Comment by penx** [comment]
@MichaelDeBoey thanks for merging, was [trying to figure out the yarn lock](https://discord.com/channels/770287896669978684/940264701785423992/1067583551836536866), which will now be out of date in main.

Hopefully will get there shortly!

**Comment by penx** [comment]
I've resolved my issue with yarn, and the root lock file seems to be fine as it doesn't contain packages for each example

**Pull request merged**
