### PR TITLE
feat: add `contentful` example

### PR DESCRIPTION
**Pull request by harshil1712**
This PR adds an example for Remix and Contentful.

The original repo can be found [here](https://github.com/contentful/starter-remix-portfolio)

### CODE REVIEW

**Review by machour — CHANGES_REQUESTED** [review]
Hey @harshil1712 and thank you so much for this contribution!

This is a legendary pull request 🥇 

However, I'm afraid a full fledged stack is too complex as per this repository guidelines, where we try to keep things rather simple:

> What makes a good example is focus. There's certainly room for examples that show off a whole app experience and we do have some examples like that. But the vast majority of useful examples are focused on a specific use-case. Otherwise it's hard for people to know what to look for in the code.
>
> This means you should avoid adding stuff that isn't absolutely necessary for the example. Start with bare bones and add only what you need.

This example should focus on the `contentful` connection, and a single collection list/view (blog for example).

Could you trim things to the bare minimum and stick to the README.md template? 🙏🏼

**Comment by chaance** [comment]
To @machour's point, this definitely feels like more of a stack instead of a repo. Perhaps in the example README you can link to your starter project for folks that want something beefier than the example integration? Users should be able to `npx create-remix --template <your repo URL>` to bootstrap the whole thing.

**Comment by MichaelDeBoey** [comment]
@harshil1712 Could you please fix the ESLint warnings/errors?

**Comment by chaance** [comment]
I'm going to actually close this one for now. @harshil1712. Let me know if you want us to share your repo as a community stack. I'm sourcing a list for some new pages on our docs and I think this would be great if you plan to maintain it!

**Pull request closed without merging**
