### PR TITLE
chore: enable `v2_routeConvention` flag

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Revival of @mcansh's #201

Got the same problem on the `pathless-routes` example though:

```sh
⚠️ Route Path Collision: "/articles"

The following routes all define the same URL, only the first one will be used

🟢 routes/articles._layout.tsx
⭕️️ routes/articles.tsx
```

### CODE REVIEW

**Comment by brophdawg11** [comment]
I think that was an old bug we fixed - I updated that example to `1.19.3` and it worked ok.  

I'm realizing most of our examples don't have v2 flags enabled 😬 .  Not a v2 blocker but we'll want to get that handled after we release.  At the moment we could probably update them all to 1.19.3?

**Comment by mcansh** [comment]
> I'm realizing most of our examples don't have v2 flags enabled 😬 . Not a v2 blocker but we'll want to get that handled after we release. At the moment we could probably update them all to 1.19.3?

yep, that was the desired result of #172 so it didnt block any v2 and each example would be incrementally updated to future flags and subsequently v2

**Comment by MichaelDeBoey** [comment]
> I'm realizing most of our examples don't have v2 flags enabled

This is the first step towards enabling all of them, but didn't want to do 1 big PR for all v2 flags (other PRs are incoming as well)

**Comment by brophdawg11** [comment]
@MichaelDeBoey yeah I agree one by one is the way to go.  Should we update them all to `1.19.3` in this PR (or a separate one) to resolve the pathless layout route issue above?  I don't have a preference if we do it here or separately - this LGTM

**Review by brophdawg11 — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@brophdawg11 I'll do it in a separate PR after merging this one

**Comment by MichaelDeBoey** [comment]
@brophdawg11 Done in #337

**Pull request merged**
