### PR TITLE
chore(_official_contacts-tutorial): update to latest pre-release

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by brophdawg11** [comment]
I don't have any of the back-story here but what's the reason this example was on nightly but I think the rest were on latest (or as we found out, pinned to 1.14).  Should we align them one way or the other?

**Comment by MichaelDeBoey** [comment]
@brophdawg11 This was one of the new tutorials @ryanflorence added to the v2 docs

**Comment by brophdawg11** [comment]
ah ok - and `nightly` now is missing latest stuff from the `release-next` branch, got it

**Comment by brophdawg11** [comment]
Maybe they should all just be `latest` eventually...

**Comment by MichaelDeBoey** [comment]
@brophdawg11 Once v2 is released and all examples are updated, we can use `*` again

**Pull request merged**
