### PR TITLE
feat(firebase): deploy to Cloud Functions for Firebase

### PR DESCRIPTION
**Pull request by penx**
Reopening https://github.com/remix-run/remix/pull/3398 against remix-run/examples

Deploy to firebase functions and hosting

Closes: Discussion at https://github.com/remix-run/remix/pull/1811#issuecomment-1050238130

- [x] Docs
- [ ] Tests (I'd happily add Playwright tests if you want these on examples)

Testing Strategy:

- Testing locally against emulator with JS enabled and disabled
- Testing locally against production with JS enabled and disabled
- Following deploy instructions and testing remote with JS enabled and disabled

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@penx Could you please fix the ESLint warnings/errors?
Most of them will probably be fixed by running `yarn lint:fix`

Please also resolve conflicts.

**Comment by penx** [comment]
@MichaelDeBoey fixed, please could you reopen? 7 days is a bit short to close :)

I had [resolved issues and fixed conflicts on 4 Oct](https://github.com/remix-run/examples/pull/5#event-7519786031) but have pushed another rebase

**Comment by machour** [comment]
Same problem here, can't reopen on my side.

**Comment by penx** [comment]
Reopened as #53

**Pull request closed without merging**
