### PR TITLE
fix(_official-blog-tutorial): fix `useActionData`/`useLoaderData` usage

### LINKED ISSUE #34: Typecheck fails on blog-tutorial example
When I run typechecking or have my editor open, the following errors are shown by typescript, even on a fresh clone of the example:
```
> typecheck
> tsc -b && tsc -b cypress

app/routes/notes/$noteId.tsx:36:16 - error TS2352: Conversion of type 'SerializeObject<Simplify<{ note: Note; } & {}>>' to 
type 'LoaderData' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, conv
ert the expression to 'unknown' first.
  The types of 'note.createdAt' are incompatible between these types.
    Type 'string' is not comparable to type 'Date'.

36   const data = useLoaderData() as LoaderData;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

app/routes/posts/$slug.tsx:23:26 - error TS2352: Conversion of type 'SerializeObject<Simplify<{ post: Post; html: string; }
 & {}>>' to type 'LoaderData' may be a mistake because neither type sufficiently overlaps with the other. If this was inten
tional, convert the expression to 'unknown' first.
  The types of 'post.createdAt' are incompatible between these types.
    Type 'string' is not comparable to type 'Date'.

23   const { post, html } = useLoaderData() as LoaderData;
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

app/routes/posts/admin.tsx:16:21 - error TS2352: Conversion of type 'SerializeObject<Simplify<{ posts: Post[]; } & {}>>' to
 type 'LoaderData' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, con
vert the expression to 'unknown' first.
  Types of property 'posts' are incompatible.
    Type 'SerializeObject<Simplify<{ createdAt: Date; updatedAt: Date; title: string; slug: string; markdown: string; } & {
}>>[]' is not comparable to type 'Post[]'.
      Type 'SerializeObject<Simplify<{ createdAt: Date; updatedAt: Date; title: string; slug: string; markdown: string; } &
 {}>>' is not comparable to type 'Post'.

16   const { posts } = useLoaderData() as LoaderData;
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

app/routes/posts/index.tsx:18:21 - error TS2352: Conversion of type 'SerializeObject<Simplify<{ posts: Post[]; } & {}>>' to
 type 'LoaderData' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, con
vert the expression to 'unknown' first.
  Types of property 'posts' are incompatible.
    Type 'SerializeObject<Simplify<{ createdAt: Date; updatedAt: Date; title: string; slug: string; markdown: string; } & {
}>>[]' is not comparable to type 'Post[]'.

18   const { posts } = useLoaderData() as LoaderData;
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.
```
What seems to be happening is that `createdAt` is a string rather than a date somewhere in between (in Prisma, maybe). A temporary workaround is to convert the result of `useLoaderData` to `unknown` and then `LoaderData`, but this isn't the best solution. This problem happens regardless of the TS version (both 4.7 and 4.8 result in an error). Is there a known solution to this?

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
See https://github.com/remix-run/remix/releases/tag/remix@1.6.5

---

Closes #34

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Same comment as the other tutorial. Thanks!

**Comment by mcansh** [comment]
unfortunately this causes a bunch of typescript errors due to only returning the error for the specific input resulting in
```ts
Property 'email' does not exist on type 'SerializeObject<UndefinedToOptional<{ email: string; }>> | SerializeObject<UndefinedToOptional<{ password: string; }>>'.
```
this should be fixable in remix itself by concatenating all the keys into a single `SerializeObject<UndefinedToOptional<{ password?: string; email?: string }>>` type, but i'm not sure if others have feelings about not doing that

**Comment by MichaelDeBoey** [comment]
> unfortunately this causes a bunch of typescript errors due to only returning the error for the specific input

@mcansh Fixed these errors


> we should probably run `tsc` on PRs like we do eslint

Although that would be a good idea to not have these issues, it will require an `npm install` (& sometimes even more, like `npx prisma migrate dev`), otherwise TypeScript will complain 😢

**Comment by mcansh** [comment]
> it will require an `npm install` (& sometimes even more, like `npx prisma migrate dev`), otherwise TypeScript will complain 😢

oof yeah that's true 😞

**Review by mcansh — APPROVED** [review]

**Comment by mcansh** [comment]
unrelated to changes here, but looks like React now wants `startTransition` to return `void` or `undefined`

```ts
app/entry.client.tsx:7:5 - error TS2322: Type 'Root' is not assignable to type 'VoidOrUndefinedOnly'.

  7     hydrateRoot(
        ~~~~~~~~~~~~
  8       document,
    ~~~~~~~~~~~~~~~
... 
 11       </StrictMode>
    ~~~~~~~~~~~~~~~~~~~
 12     )
    ~~~~~

  node_modules/@types/react/index.d.ts:1107:38
    1107     export type TransitionFunction = () => VoidOrUndefinedOnly;
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.


Found 1 error.

error Command failed with exit code 1.
```

```diff
-  startTransition(() =>
+  startTransition(() => {
    hydrateRoot(
      document,
      <StrictMode>
        <RemixBrowser />
      </StrictMode>
    )
-  );
+  });

**Comment by MichaelDeBoey** [comment]
> unrelated to changes here, but looks like React now wants `startTransition` to return `void` or `undefined`

I'll create a separate PR for it 👍

**Comment by mcansh** [comment]
> I'll create a separate PR for it 👍

😬 https://github.com/remix-run/examples/pull/91 - you can take on the templates if you'd like 😉

**Comment by MichaelDeBoey** [comment]
> oof yeah that's true 😞

Would love to find a solution for this though 🤔

Maybe a `setup` script for all extra stuff that needs to happen in order to make TS happy? 🤔

It would still take a long time to run `npm install && npm -s setup` on all the example folders though 🤔😕

**Comment by mcansh** [comment]
unless we can tell which example changed and only run tsc on that

**Comment by MichaelDeBoey** [comment]
@mcansh Created an issue to discuss it further: https://github.com/remix-run/examples/issues/92

**Pull request merged**
