### PR TITLE
feat: add AWS SDK v3 upload example

### PR DESCRIPTION
**Pull request by janhesters**
Closes https://github.com/remix-run/examples/issues/163

## Description

- Moves the "old" S3 upload example in a different folder and calls out that its for an old version of the S3 SDK.
- Adds a new example for the new AWS S3 SDK v3.

### CODE REVIEW

**Review by akashpayne — COMMENTED** [review]
Love it

**Review by akashpayne — APPROVED** [review]

**Comment by janhesters** [comment]
@akashpayne What needs to get done for this to get merged?

**Comment by akashpayne** [comment]
@mcansh @MichaelDeBoey

**Review by mcansh — COMMENTED** [review]
LGTM, the one thing that might be confusing as is, is that `file-and-s3-upload-v2` sounds newer than `file-and-s3-upload`. can we make it `file-and-s3-upload-v2` and `file-and-s3-upload-v3` instead?

**Comment by janhesters** [comment]
@mcansh of course! I'll try and update the code and the branch this weekend, as this week is full with work 👌

**Comment by janhesters** [comment]
@MichaelDeBoey Yes! However, I need to find the time 🙏

**Pull request closed without merging**
